create table projects (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    subtitle varchar(255),
    description text not null,
    tags varchar(255),
    hero_image varchar(255),
    featured boolean not null default false,
    created_at timestamp not null
);

create table contact_messages (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(180) not null,
    message text not null,
    created_at timestamp not null
);
